apiVersion: v1
kind: Pod
metadata:
  name: po-hasher
spec:
  containers:
    -
      args:
        -
          hasher.rb
      command:
        -
          rubi
      env:
        -
          name: autor
          value: Gemma
      image: gemmadockerid/ruby:sinatra-thin hasher.rb
      name: hasher
      ports:
        -
          containerPort: 80
          protocol: TCP
      VolumeMounts:
        -
          mountPath:  /data/hasher.rb
          name: volume-hasher
          readOnly: true
          subPath: hasher.rb
      workingDir: /data/
  restartPolicy: Always
  volumes:
    -
      name: volume-hasher
      secret:
        defaultMode: 0400
        items:
          -
            key: hasher.rb
            mode: 0400
            path: hasher.rb
        secretName: secret-hasher
